### ISSUE TITLE
正常编译但是无法使用daplink烧录

### ISSUE THREAD

**Issue by 654955321** [ArteryTek/platform-arterytekat32#16]
![image](https://github.com/ArteryTek/platform-arterytekat32/assets/9605294/00b02cf9-415c-47f2-9a8d-f392c66d79e5)
上图编译正常但是无法使用daplink下载；排除设备问题。我在keil中可以正常识别daplink并烧录。
![image](https://github.com/ArteryTek/platform-arterytekat32/assets/9605294/b76afa27-76c2-45a7-b5e5-b5ac09deb1f5)
使用的立创开源的开发板：https://oshwhub.com/fanhuacloud/at32f435_dev
请帮助我解决下 谢谢。

**Comment by amoxu** [comment]
从报错信息看，是openocd的接口默认指定了不支持的JTAG口，而非SWD口，建议您尝试以下方法：
1. 将platformio.ini中的upload_protocol及debug_tool都改成atlink或者atlink_dap_v2尝试一下。
2. 如果1无法正常使用，请使用PlatformIO菜单中的Advanced->Verbose Upload，并在本贴中贴出控制台的命令执行结果。

**Comment by 654955321** [comment]
感谢你的回复。
经测试1无法正常使用；
下面是Verbose Upload命令截图：
![image](https://github.com/ArteryTek/platform-arterytekat32/assets/9605294/16714090-a0e3-4114-b833-5388b3490deb)
![image](https://github.com/ArteryTek/platform-arterytekat32/assets/9605294/16869651-e98e-4709-b60b-ecbf864b0c6d)

**Comment by amoxu** [comment]
请在Windows的设备管理器界面，截图展示一下这个CMSIS-DAP设备的名称。

**Comment by 654955321** [comment]
以下是CMSIS-DAP设备的名称截图:
![image](https://github.com/ArteryTek/platform-arterytekat32/assets/9605294/31546770-ab4b-480d-8dc3-89d0bf9b68d6)
![image](https://github.com/ArteryTek/platform-arterytekat32/assets/9605294/d0af9a6a-fc34-40e5-9875-9cebd9a3f4b1)
![image](https://github.com/ArteryTek/platform-arterytekat32/assets/9605294/2cfbda8b-1daf-4df6-9526-953b4580f07c)

**Comment by amoxu** [comment]
您所截图的是虚拟串口，请在Windows设备管理列表中找到名字中带有"CMSIS-DAP"的“通用串行总线设备”，参考如下：
![image](https://github.com/ArteryTek/platform-arterytekat32/assets/4747759/a6231237-2f7e-4e19-b1a2-e4908b02af5f)

根据您所说的开发板的项目页的信息，该板带的是WCH-Link，目前不太确定WCH-Link在电脑之识别到的名称是否会包含“CMSIS-DAP”，如果没有，则暂时不受OpenOCD的支持。

**Comment by 654955321** [comment]
好的 WCH-Link驱动可能只能被keil识别  我买了带atlink的开发板 pio编译和烧录均正常。 谢谢
