### ISSUE TITLE
能是否加入F423等新推出的開發版支援

### ISSUE THREAD

**Issue by neko0xff** [ArteryTek/platform-arterytekat32#17]
不好意思打擾了，我按照你們的官方文件(AN0186)對PlatformIO進行配置，但到了選擇開發版的部分則無F423等新推出的開發版支援.

**Comment by amoxu** [comment]
很抱歉给您带来困扰，我会在接下来几天，完成更新。

**Comment by amoxu** [comment]
抱歉，该仓库并非官方在维护，所以有些滞后，现在已经完成全部更新，感谢支持。
