### ISSUE TITLE
可以增加Macos ARM的openocd 的支持么？

### ISSUE THREAD

**Issue by sakunamary** [ArteryTek/platform-arterytekat32#20]
可以增加Macos ARM的openocd 的支持么？谢谢啦

**Comment by amoxu** [comment]
您可以使用以下指令更新一下工具
`pio pkg update -g -t tool-openocd-at32  `

**Comment by sakunamary** [comment]
![image](https://github.com/user-attachments/assets/f498c585-b023-4035-a3ff-0f1dac653688)

顺利成功～！烧录和debug都是成功的！我是把整个旧的platfom 跟 package 都删了，重新安装。用的是DAP-link。 芯片是AT32F421 的，MACmini M2 OS14.6.1。
