### ISSUE TITLE
编译出的hex文件地址范围不正确

### ISSUE THREAD

**Issue by yueduz** [ArteryTek/platform-arterytekat32#5]
![1ff0f05214d8d69c](https://user-images.githubusercontent.com/1448159/184871033-fead9577-53d5-4828-9f56-1364fb5e8506.png)
#

**Comment by amoxu** [comment]
建议您分析一下编译成功后项目文件夹下.pio/build/[env变量]/linkmap.map文件。
或者上传来我们帮助你分析一下。

- _部分操作系统在文件浏览器中.pio属于隐藏文件夹，在VSCode中可以导航到_
- _linkmap中包含部分项目相关结构，及用户目录等部分涉及隐私信息，请核对确认文件内容不会泄漏您的隐私或机密，或者您仅需提供.text 段的始末相关行内容及.data 段的始末相关行内容_

**Comment by yueduz** [comment]
是因为在linux下区分大小写的关系，未正确找到ld和s文件
