### ISSUE TITLE
arm-none-eabi-as：未识别的选项 ‘-x’

### ISSUE THREAD

**Issue by yueduz** [ArteryTek/platform-arterytekat32#6]
我在Linux下工作，Linux 区分大小写。所以我对platform-arterytekat32 做了图1更改，但是我得到图2
![截图 2022-08-21 18-24-22](https://user-images.githubusercontent.com/1448159/185786740-9908af7b-3694-4fc4-8272-6cf442286cbb.png)
![截图 2022-08-21 18-22-30](https://user-images.githubusercontent.com/1448159/185786747-5135061f-09a1-43ec-8117-166e61e0bd8c.png)
.

**Comment by amoxu** [comment]
已收到您的反馈，近期会集中测试一下Linux下的支持度，并完善烧录及调试工具的支持。
感谢您的反馈。

**Comment by amoxu** [comment]
Linux支持已经过测试并发布，您可以通过在PIO CLI中执行如下指令更新至最新版本
`pio pkg install -g -p https://github.com/ArteryTek/platform-arterytekat32/releases/download/v1.0.2/pio-at32-1.0.2.tar.gz`
欢迎您测试并提供反馈意见
