### ISSUE TITLE
include/usb_conf.h:37:10: fatal error: at32f435_437_board.h: No such file or directory

### ISSUE THREAD

**Issue by yueduz** [ArteryTek/platform-arterytekat32#7]
![截图 2022-09-15 10-32-51](https://user-images.githubusercontent.com/1448159/190299973-b483e92f-98be-4382-858f-6915613b2c69.png)
当我将 "usb_conf.h” 放到 "./include/"目录时，提示： include/usb_conf.h:37:10: fatal error: at32f435_437_board.h: No such file or directory；
当我将 "usb_conf.h” 放到 "./lib/inc/"目录时，编译正常。

我是从 https://github.com/amoxu/platform-arterytekat32 安装的platform-arterytekat32包。

**Comment by amoxu** [comment]
PlatformIO的库依赖查找原理请参考[Library Dependency Finder (LDF)](https://docs.platformio.org/en/stable/librarymanager/ldf.html#id2)。
这里我建议您把usb_drivers整个目录放入lib目录下。

**Comment by amoxu** [comment]
> PlatformIO的库依赖查找原理请参考[Library Dependency Finder (LDF)](https://docs.platformio.org/en/stable/librarymanager/ldf.html#id2)。 这里我建议您把usb_drivers整个目录放入lib目录下。

lib目录下的每一个文件夹，都会被当作一个独立的库编译，最后再编译src文件夹下的对象，最后最通过链接生成目标文件。
您可以看一下编译完成后项目文件夹下的.pio/build/<BOARDNAME>下的编译中间文件了解一下编译过程的结构。

**Comment by yueduz** [comment]
“platformio.ini” 中
```
 build_flags = -Iinclude
```
“include”目录引入的头文件无法include “lib”目录中的头文件，“lib”目录中的头文件也无法include “include”目录中的头文件。而“
framework-at32firmlib”框架却要使用“ build_flags = -Iinclude”指定的头文件，不能使用“lib”目录中的头文件。

**Comment by amoxu** [comment]
> “platformio.ini” 中
> 
> ```
>  build_flags = -Iinclude
> ```
> 
> “include”目录引入的头文件无法include “lib”目录中的头文件，“lib”目录中的头文件也无法include “include”目录中的头文件。而“ framework-at32firmlib”框架却要使用“ build_flags = -Iinclude”指定的头文件，不能使用“lib”目录中的头文件。

build_flags中要加入include目录的目的是因为BSP会引用at32f<bsp_name>_conf.h文件，而这个文件通常是用户可修改的，因此被放到了include目录下，但platformio在编译lib（bsp中的cmsis和driver都是以lib分别编成库）的时候默认不会引入include做为头文件查找目录，所以才需要在platformio.ini中手动加入。

lib目录不会直接被加入include搜索目录，但lib目录下的二级目录会被当做单独的库进行编译，例如lib/foo/，所以这些二级目录会被加入includePath；您可以在项目的.vscode目录下查看c_cpp_properties.json了解被加入的includePath。

您也可以在Platformio的PROJECT TASKS => Advanced中找到Verbose Build，然后从终端输出中看一下对应的源码在编译时传入的-I目录查找参数。
