### ISSUE TITLE
fatal error: at32f435_437_conf.h: No such file or directory

### ISSUE THREAD

**Issue by W-Mai** [ArteryTek/platform-arterytekat32#9]
创建一个`genericAT32F435RGT7`的项目，并将修改后的`at32f435_437_conf.h`文件放在创建的pio项目的`include`目录下，re-init项目后，编译仍然报错。

开发环境: CLion + PlatformIO插件 + macOS

**Comment by amoxu** [comment]
#7 中的说明供您参考

**Comment by W-Mai** [comment]
> #7 中的说明供您参考

🙏🏿谢谢
